const express = require('express');
const router = express.Router();
const DashbBoard = require('../controllers/dashboardController');
router.get('/promedio_velocidad/:nombreTabla/:idAnalisis', DashbBoard.promedioVelocidad);
router.get('/promedio_fertilizacion_dosis_real/:idAnalisis', DashbBoard.promedioFertilizacionDosisReal);
router.get('/promedio_altura_m/:idAnalisis', DashbBoard.promedioAlturaGps);
router.get('/tiempo_total_actividad/:nombreTabla/:idAnalisis', DashbBoard.tiempoTotalActividad);
router.get('/eficiencia/:nombreTabla/:idAnalisis', DashbBoard.eficiencia);
router.get('/presion_contador/:idAnalisis', DashbBoard.presionContadorBase);
router.get('/promedio_tch/:nombreTabla/:idAnalisis',DashbBoard.promedioTch);
router.get('/operador/:nombreTabla/:idAnalisis',DashbBoard.operador);
router.get('/fecha_actividad/:nombreTabla/:idAnalisis',DashbBoard.fechaActividad);
router.get('/ultimo_analisis/:tipoAnalisis/:idUsuario', DashbBoard.obtenerUltimoAnalisis);
router.get('/execPython/:idUsuario/:idAnalisis', DashbBoard.execPython);
router.get('/execBash/:idUsuario/:idAnalisis', DashbBoard.execBash);
module.exports = router;